[server]
enableXsrfProtection = false
enableCORS = false
[theme]
primaryColor="#0B6623"         # dark green
backgroundColor="#FFFFFF"      # white
secondaryBackgroundColor="#FFFFFF"  # dark green sidebar
textColor="#0B6623"            # main text dark green
font="sans serif"